vich_uploader:
    db_driver: orm

    mappings:
        log_image:
            uri_prefix: /images/logs
            upload_destination: '%kernel.project_dir%/public/images/logs'
        galery_image:
            uri_prefix: /images/galery
            upload_destination: '%kernel.project_dir%/public/images/galery'


    # mappings:
    #     log_image:
    #         uri_prefix: /images/logs
    #         upload_destination: '%kernel.project_dir%/public/images/logs'
